[workspace]
members = ["node-manager", "nmgrd"]

# RSA operations are slow, we want the tests to be fast, even in debug mode
[profile.dev.package."rsa"]
opt-level = 3
[profile.dev.package."num-bigint-dig"]
opt-level = 3
